# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that publishes AML Pipeline for model training

# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     include:
#     - azure-pipelines/1-training-build/*
#     - operation/execution/training_pipeline.py
#     - src/

# TODO: define proper paths

variables:
- template: ../pipelines-configuration.yml
- template: ../../infra-configuration.yml
# TODO: reorganize variables once finished

pool:
  vmImage: ubuntu-latest

stages:

- stage: tests
  displayName: 'Run Code Tests'
  jobs:
  - template: run-training.template.yml

- stage: training_build
  displayName: 'Publish Training AML Pipeline'
  dependsOn: tests
  jobs:
    - job: training_build
      displayName: 'Publish Training AML Pipeline'
      steps:

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7

        - task: AzureCLI@1
          displayName: 'Publish Training AML Pipeline'
          inputs:
            azureSubscription: $(DEV_SERVICECONNECTION_WS)
            scriptLocation: inlineScript
            inlineScript: |
              # Install dependencies
              dependencies="azureml-sdk==$(SDK_VERSION)"
              python -m pip install --upgrade pip && python -m pip install $dependencies
              # Create/update training pipeline
              trainingbuild_script=operation/execution/training_pipeline.py
              python $trainingbuild_script

#TODO arguments and location of path definitions
