# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that publishes AML Pipeline for model training

trigger:
- none

# trigger:
#   branches:
#     include:
#     - develop
#   paths:
#     include:
#     - azure-pipelines/1-training-build/*
#     - operation/execution/training_pipeline.py
#     - src/
# TODO: define proper triggers and paths 

variables:
- template: ../../configuration/configuration-aml.variables.yml
- template: ../../configuration/configuration-infra.variables.yml
# TODO: reorganize variables once finished

pool:
  vmImage: ubuntu-latest

stages:

#########################################
##  DEPLOY IN ACI (dev/test purposes)  ##
#########################################

- stage: deploy_model_aci
  displayName: 'Deploy Model to ACI'
  jobs:
  - template: deploy-model.template.yml
    parameters:
      environment: DEV
      deploymentType: aci
      webserviceName: $(AML_WEBSERVICE)-aci
  
  # - job: delete_aci
  #   displayName: 'Delete ACI Webservice'
  #TODO


#####################
##  DEPLOY IN AKS  ##
#####################

- stage: deploy_model_aks
  displayName: 'Deploy Model to AKS'
  dependsOn: deploy_model_aci
  jobs:
  - template: deploy-model.template.yml
    parameters:
      environment: DEV
      deploymentType: aks
      webserviceName: $(AML_WEBSERVICE)
