# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  DEV_RESOURCE_GROUP: mlops-uc-sales
  DEV_LOCATION: westeurope
  DEV_NAMESPACE: mlouc1d
  DEV_SERVICECONNECTION_RG: conn_mlouc1_rg
  DEV_SERVICECONNECTION_WS: conn_mlouc1d_ws
  DEV_AMLWORKSPACE: $(DEV_NAMESPACE)aml
  DEV_STORAGEACCOUNT: $(DEV_NAMESPACE)sa
  DEV_KEYVAULT: $(DEV_NAMESPACE)kv
  DEV_APPINSIGHTS: $(DEV_NAMESPACE)ai
  DEV_CONTAINERREGISTRY: $(DEV_NAMESPACE)cr

  # TEST Environment
  TEST_RESOURCE_GROUP: mlops-uc-sales
  TEST_LOCATION: westeurope
  TEST_NAMESPACE: mlouc1t
  TEST_SERVICECONNECTION_RG: conn_mlouc1_rg
  TEST_SERVICECONNECTION_WS: conn_mlouc1t_ws
  TEST_AMLWORKSPACE: $(TEST_NAMESPACE)aml
  TEST_STORAGEACCOUNT: $(TEST_NAMESPACE)sa
  TEST_KEYVAULT: $(TEST_NAMESPACE)kv
  TEST_APPINSIGHTS: $(TEST_NAMESPACE)ai
  TEST_CONTAINERREGISTRY: $(TEST_NAMESPACE)cr

  # PRD Environment
  PRD_RESOURCE_GROUP: mlops-uc-sales
  PRD_LOCATION: westeurope
  PRD_NAMESPACE: mlouc1p
  PRD_SERVICECONNECTION_RG: conn_mlouc1_rg
  PRD_SERVICECONNECTION_WS: conn_mlouc1p_ws
  PRD_AMLWORKSPACE: $(PRD_NAMESPACE)aml
  PRD_STORAGEACCOUNT: $(PRD_NAMESPACE)sa
  PRD_KEYVAULT: $(PRD_NAMESPACE)kv
  PRD_APPINSIGHTS: $(PRD_NAMESPACE)ai
  PRD_CONTAINERREGISTRY: $(PRD_NAMESPACE)cr
