# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of AML-related environment variables

variables:

  SDK_VERSION: 1.20
  
  AML_DATASET: ""
  AML_MODEL_NAME: ""

  # Training
  TRAINING_EXPERIMENT: ""
  TRAINING_PIPELINE: ""
  TRAINING_COMPUTE: cpucompute

  # Batch inference
  BATCHINFERENCE_EXPERIMENT: ""
  BATCHINFERENCE_PIPELINE: ""
  BATCHINFERENCE_COMPUTE: $(TRAINING_COMPUTE)

  # Real-time inference
  AKS_COMPUTE: aks-compute
  AML_WEBSERVICE: webservice
