# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  DEV_RESOURCE_GROUP: rg-mlops-template-dev-001
  DEV_LOCATION: westeurope
  DEV_NAMESPACE: mlopsdevtmpl
  DEV_SERVICECONNECTION_RG: conn-mlops-sub-infra
  DEV_SERVICECONNECTION_WS: conn-mlops-aml-bsc-dev-tmpl
  DEV_AMLWORKSPACE: aml$(DEV_NAMESPACE)
  DEV_STORAGEACCOUNT: sa$(DEV_NAMESPACE)
  DEV_KEYVAULT: kv$(DEV_NAMESPACE)
  DEV_APPINSIGHTS: ai$(DEV_NAMESPACE)
  DEV_CONTAINERREGISTRY: cr$(DEV_NAMESPACE)

  # PRD Environment
  PRD_RESOURCE_GROUP: rg-mlops-template-prod-001
  PRD_LOCATION: westeurope
  PRD_NAMESPACE: mlopsprodtmpl
  PRD_SERVICECONNECTION_RG: conn-mlops-sub-infra
  PRD_SERVICECONNECTION_WS: conn-mlops-aml-bsc-prod-tmpl
  PRD_AMLWORKSPACE: aml$(PRD_NAMESPACE)
  PRD_STORAGEACCOUNT: sa$(PRD_NAMESPACE)
  PRD_KEYVAULT: kv$(PRD_NAMESPACE)
  PRD_APPINSIGHTS: ai$(PRD_NAMESPACE)
  PRD_CONTAINERREGISTRY: cr$(PRD_NAMESPACE)
