# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for deploying Azure Machine Learning pipelines

parameters:
- name: environment
  type: string
- name: jobName
  type: string
- name: jobDisplayName
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspace
  type: string
- name: deploymentScript
  type: string


jobs:

- job: build_code
  displayName: 'Build code to deploy'
  steps:

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'DeploymentCode'
        targetPath: '$(Build.SourcesDirectory)'

- deployment: ${{parameters.jobName}}
  displayName: ${{parameters.jobDisplayName}}
  dependsOn: build_code
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:

          - task: DownloadPipelineArtifact@2
            displayName: 'Download deployment code'
            inputs:
              artifact: 'DeploymentCode'
              path: $(System.ArtifactsDirectory)/deploymentcode/

          - template: run-aml-python-code.template.yml
            parameters:
              serviceConnection: ${{parameters.serviceConnection}}
              resourceGroup: ${{parameters.resourceGroup}}
              amlWorkspace: ${{parameters.amlWorkspace}}
              scriptPath: $(System.ArtifactsDirectory)/deploymentcode/${{parameters.deploymentScript}}
              scriptArguments: --version  $(Build.BuildId)
              scriptExtraDependencies: pyyaml
