# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that publishes AML Pipeline for model training

trigger:
- none

# trigger:
#   branches:
#     include:
#     - develop
#   paths:
#     include:
#     - azure-pipelines/1-training-build/*
#     - operation/execution/training_pipeline.py
#     - src/
# TODO: define proper triggers and paths 

variables:
- template: ../configuration/configuration-aml.variables.yml
- template: ../configuration/configuration-infra.variables.yml

pool:
  vmImage: ubuntu-latest

stages:

#TODO tests
# - stage: tests
#   displayName: 'Run Code Tests'
#   jobs:
#   - template: templates/run-code-tests.template.yml


#########################
##  UPDATE BATCH DATA  ##
#########################

# Reusing data from training for demonstration purposes only.
# In real scenarios, a different template pipeline would be required for updating batch inference data.
- stage: update_data
  displayName: 'Update Data for Batch Inference'
  # dependsOn: tests
  jobs:
  - template: templates/update-data.template.yml
    parameters:
      serviceConnection: $(DEV_SERVICECONNECTION_WS)
      resourceGroup: $(DEV_RESOURCE_GROUP)
      amlWorkspace: $(DEV_AMLWORKSPACE)


###########################
##  RUN BATCH INFERENCE  ##
###########################

- stage: batch_inference
  displayName: 'Run Batch Inference'
  dependsOn: update_data
  jobs:

    - job: batch_inference_build
      displayName: 'Publish Batch Inference AML Pipeline'
      steps:
      - template: templates/utils/run-aml-python-code.template.yml
        parameters:
          serviceConnection: $(DEV_SERVICECONNECTION_WS)
          resourceGroup: $(DEV_RESOURCE_GROUP)
          amlWorkspace: $(DEV_AMLWORKSPACE)
          scriptPath: operation/execution/build_batch_scoring_pipeline.py
          scriptExtraDependencies: pyyaml
          scriptArguments: --model-name $(AML_MODEL)

    - template: templates/utils/invoke-aml-pipeline.template.yml
      parameters:
        dependsOn: batch_inference_build
        jobDisplayName: 'Invoke Batch Inference AML Pipeline'
        serviceConnection: $(DEV_SERVICECONNECTION_WS)
        resourceGroup: $(DEV_RESOURCE_GROUP)
        amlWorkspace: $(DEV_AMLWORKSPACE)
        pipelineName: $(BATCHINFERENCE_PIPELINE)
        experimentName: $(BATCHINFERENCE_EXPERIMENT)
